; Script generated by Modern UI 2
!include "MUI2.nsh"

; General
Name "GeldeSat VPN"
OutFile "dist\GeldeSat-VPN-Setup.exe"
InstallDir "$LOCALAPPDATA\GeldeSat VPN"
InstallDirRegKey HKCU "Software\GeldeSat VPN" ""
RequestExecutionLevel user

; Interface Settings
!define MUI_ABORTWARNING

; Pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "d:\Sites\ggl ag\vpnugulaması\resources\xray\LICENSE" ; Using Xray license as placeholder or remove if none
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Languages
!insertmacro MUI_LANGUAGE "Turkish"

; Installer Sections
Section "GeldeSat VPN" SecDummy

  SetOutPath "$INSTDIR"
  
  ; Files to include
  File /r "d:\Sites\ggl ag\vpnugulaması\dist\GeldeSat VPN-win32-x64\*.*"
  
  ; Store installation folder
  WriteRegStr HKCU "Software\GeldeSat VPN" "" $INSTDIR
  
  ; Create uninstaller
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  
  ; Create shortcuts
  CreateDirectory "$SMPROGRAMS\GeldeSat VPN"
  CreateShortCut "$SMPROGRAMS\GeldeSat VPN\GeldeSat VPN.lnk" "$INSTDIR\GeldeSat VPN.exe"
  CreateShortCut "$SMPROGRAMS\GeldeSat VPN\Uninstall.lnk" "$INSTDIR\Uninstall.exe"
  CreateShortCut "$DESKTOP\GeldeSat VPN.lnk" "$INSTDIR\GeldeSat VPN.exe"

SectionEnd

; Uninstaller Section
Section "Uninstall"

  RMDir /r "$INSTDIR"
  RMDir "$SMPROGRAMS\GeldeSat VPN"
  Delete "$DESKTOP\GeldeSat VPN.lnk"

  DeleteRegKey /ifempty HKCU "Software\GeldeSat VPN"

SectionEnd
